date and time can now be set
DGovi/soen343house pull request #30
Opened 2020-10-18 15:45 UTC by DGovi

2020-10-18 23:45 UTC, adrientremblay requested changes

2020-10-18 23:45 UTC, adrientremblay commented on soen343house.iml
> -    <orderEntry type="module-library">
I need this whole block for intelliJ to be able to find org.json.JSONException  :(

2020-10-18 23:45 UTC, adrientremblay commented on soen343house.iml
> +    <orderEntry type="library" name="dependencies" level="project" />
because of the way i have my libraries set up  name needs to be 'jfxrt' for me.  We should keep this consistent as a group.  Is this break your guy's intelliJ?  @MahadJanjua  @genericalexacc  @jmezaber ?

2020-10-18 23:45 UTC, adrientremblay commented on src/View/Dashboard.fxml
> +                        <Label fx:id="dateLabel" prefHeight="17.0" prefWidth="133.0" text="Date is:" />
Im getting ...s because of some width issues with the labels.

![image](https://user-images.githubusercontent.com/8109538/96387888-66e30f80-1173-11eb-881d-80f8da594361.png)

2020-10-19 02:36 UTC, DGovi commented on soen343house.iml
> -    <orderEntry type="module-library">
very cool ill put it back

2020-10-19 02:36 UTC, DGovi commented on src/View/Dashboard.fxml
> +                        <Label fx:id="dateLabel" prefHeight="17.0" prefWidth="133.0" text="Date is:" />
thanks i missed this!

2020-10-19 02:45 UTC, DGovi commented on soen343house.iml
> -    <orderEntry type="module-library">
nvm it gives me a bunch of errors when I add it

2020-10-19 03:52 UTC, adrientremblay commented on src/Controller/DashboardController.java
> +	public void displayDate(javafx.event.ActionEvent actionEvent) {
I just realized that these two methods do not update the actual date and time parameters of the simulation class.  I would look at Mahad's createUser() method for inspiration.  Essentially it just calls an associated method within the Simulation class that has all the logic within it.   That returns a string which will be the  result message thats printed to console.  Then the updateDashboard() is the method that actually changes the label values from the values that are in the simulation class.

2020-10-19 21:16 UTC, adrientremblay requested changes
Everything works and is good to go except that the methods inside DashboardController do not actually update sim (see comment).  Also we might need to add more to the javadocs because I watched the professor's lecture on javadocs and he was like "add more detail then what is visible from the class name" for javadocs.  But as a baseline they're def good.

2020-10-19 21:16 UTC, adrientremblay commented on src/Controller/DashboardController.java
> +	 * User is deleted from teh simulation and can no longer use
"teh"

2020-10-19 21:16 UTC, adrientremblay commented on src/Controller/DashboardController.java
> +	 * On a given house layout, draw the windoes at specified location
"windoes"

2020-10-19 21:16 UTC, adrientremblay commented on src/Controller/DashboardController.java
> +	public void displayDate(javafx.event.ActionEvent actionEvent) {
yeah so I everything works but as I sad before we should set the data and time parameters for the Simulation class.  Also this logic should be moved inside methods of the simulation class.  Look at the createUser() method or my set-house-location branch (which has a PR open) for inspiration.

2020-10-19 22:29 UTC, DGovi commented on src/Controller/DashboardController.java
> +	 * On a given house layout, draw the windoes at specified location
bruh ahahahah

2020-10-20 02:30 UTC, adrientremblay approved these changes

2020-10-20 02:58 UTC, merged